### ISSUE TITLE
Дробление методов isNewOrderIsRecorded и verifyEntriesAreInDbWithCard

### ISSUE THREAD

**Issue by sSlideR** [sSlideR/QA-diploma#11]
Не очень мне нравится реализация ваших методов isNewOrderIsRecorded и verifyEntriesAreInDbWithCard. Постарайтесь поделить каждый из этих методов на два и вызывать именно тот, который необходим в данный момент. Вы же в тесте должны знать, куда и какая информация запишется при любом тестовом случае. Если должен быть отказ по кредитке, то проверяем именно отказ по кредитке и тд. if-else нужно по возможности избегать, здесь мы точно можем от них избавиться.

**Comment by sSlideR** [comment]
Метод isNewOrderIsRecorded включает в себя условный код, т.к. есть 2 ситуации: когда база пустая и когда в базе уже есть какие-то записи. Не совсем понимаю зачем его разделять, ведь по сути нам без разницы пустая база или чем-то наполнена. Нам главное убедиться, что в базу добавлен новый запрос на покупку тура.
https://github.com/sSlideR/QA-diploma/blob/aa83fbc7ca0853335d5ef522079c17b4c85bb6b4/src/test/java/DataHelper/DataBase.java#L31-L48

**Comment by ArRomanov** [comment]
Посмотрел логику более подробно и, получается, в вашей реализации такой подход будет ок. Можно было изначально сделать два варианта:
1. Очищать после таблицу после каждого теста и проверять лишь наличие записи, но не сравнивать.
2. Можно было в `OrderEntity` переопределить метод equals и сравнивать объекты целиком, а не по отдельным полям, чтобы избежать проверки на null.

Пусть тогда остается как есть.
