### ISSUE TITLE
Реструктуризация классов по работе с SQL

### ISSUE THREAD

**Issue by sSlideR** [sSlideR/QA-diploma#9]
Методы из классов *Entity лучше переместить в отдельный класс с sql запросами, а в entity оставить только поля, так будет корректнее. Весь код для работы с sql можно переместить в отдельный пакет SqlUtils, например.

**Comment by sSlideR** [comment]
Ошибочный коммит https://github.com/sSlideR/QA-diploma/commit/a8f427c8408eec36189850610cc4c2413c3350c8

**Comment by sSlideR** [comment]
Не совсем понимаю как передать в метод getLastDbItem объект .class нужного типа.
В текущем виде в каждом классе *Entitiy BeanHandler<> использует соответствующий класс на выходе (напр.: new BeanHandler<>(OrderEntity.class)). Можно ли как-то передавать класс динамически в параметры метода?
Иначе не совсем понятно как вынести методы по работе с БД в отдельный класс, чтобы они понимали, что нужно вернуть.

https://github.com/sSlideR/QA-diploma/blob/aa83fbc7ca0853335d5ef522079c17b4c85bb6b4/src/test/java/DataHelper/DataBaseElements/OrderEntity.java#L25-L35

**Comment by sSlideR** [comment]
Через метод который сделает return класс нужного типа?

**Comment by ArRomanov** [comment]
Передавать имя класса не нужно, это должно быть уже в методе. Если два одинаковых метода, то пусть будут два одинаковых метода, пусть используют разные энтити внутри и называются по разному
